version: '3'

services:
  redis: 
    image: redis
    ports:
      - 127.0.0.1:6379:6379
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 0ff27b2d88a16cbd12ee0f72aae2f00f6fdeb05b
    ports:
      - 127.0.0.1:5432:5432